apiVersion: skaffold/v4beta14
kind: Config
build:
  artifacts:
    - image: marufamukadam/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: marufamukadam/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: marufamukadam/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: marufamukadam/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: marufamukadam/posts
      context: post
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: marufamukadam/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}